### ISSUE TITLE
Suggestion: give required Node version

### ISSUE THREAD

**Issue by PhiLhoSoft** [hellofresh/css-in-js-perf-tests#15]
I followed the instructions (on Windows 10) and when I ran the tests, I got a syntax error on the generated JS code for Aphrodite. It looked OK, but it was ES6 code, so I guessed that was my version of Node.js that choked on this code...
Indeed, I had _node v4.4.5_, installed some months ago (I think v. 6 wasn't stable then).
OK, that's a good opportunity to install v. 6.9.2...
And then the bench ran flawlessly.

The Node.js version is given in the readme with your test specs, along with the Mac version.
I suggest to indicate the required version in the Usage section.

BTW, I appreciate your implementation, you managed to make it view-library-agnostic, well done! 😄

**Comment by PepijnSenders** [comment]
Hey @PhiLhoSoft, thanks for your appreciation and trying it out. You can actually see it here: https://github.com/hellofresh/css-in-js-perf-tests/blob/master/.babelrc#L2. We compile down to node6. I agree with you that we should maybe make it a bit more clear though, so I'll add it to the README 😄.
