### ISSUE TITLE
Some issues with nested-test' styles

### ISSUE THREAD

**Issue by PhiLhoSoft** [hellofresh/css-in-js-perf-tests#19]
I make this issue mostly to get a reference for my next PR, ie. I am already trying to fix them... 😄 

I made a view.js similar to index.js (currently only for nested-test), but instead of doing a benchmark, it runs each test case only once, gets its generated HTML and outputs it to a file.
This was done to see what each generated styles and class names look like.
Again, I did some refactoring, moving the main HTML generation from test cases to render.js (making a renderHtml and a renderBody functions).
I also reworked the style, as the `:active` pseudo-class makes no sense for the container. I moved it to the button instead, and changed some other things as well, to make them visually more distinctive.

I also made units explicit, some libraries doesn't understand that `padding: 50` means `padding: '50px'` and leaves the naked number. Beside, I prefer this explicit style... 😉 

I noticed some issues with the generated code. free-style generated the code for the pseudo-classes separating them with a space, making them not working at all. I saw that I need to prefix them with `&` to make them to stick to the generated class names... But some libraries doesn't understand this prefix (while others accept either form), so I wrapped the style generations in functions to make the prefixing conditional.

Another problem: JSS doesn't like the nested syntax. The JSS with preset just ignore sub-objects (except media queries, correctly handled), while the JSS without preset just render them with `toString()`, resulting in stuff like `:hover: [object Object];` and `@media (max-height: 400px): [object Object];`...
I have to read JSS doc to see how to handle these cases.

Fixing these issues will change a bit the results of the benchmarks (generated size, probably a bit speed too).

**Comment by PhiLhoSoft** [comment]
JSS with preset only needed the prefix to the pseudo-classes, otherwise it just discards them.

**Comment by PhiLhoSoft** [comment]
OK, for JSS without preset, I have to apply the *jss-nested* plugin. Only for the *nested-test*, of course, to avoid slowing down the other tests...

**Comment by PepijnSenders** [comment]
I'm okay with adding that, good job!

**Comment by PhiLhoSoft** [comment]
Fixed by my PRs. Thanks for merging them in. 👍
