### ISSUE TITLE
styled-components

### ISSUE THREAD

**Issue by mxstbr** [hellofresh/css-in-js-perf-tests#3]
Just found this repo, looks great!

While I'm pretty sure we won't be very fast, I'd love to see [`styled-components`](https://styled-components.com) added to make sure we stay on top of our performance when making big changes. Any chance that's coming?

**Comment by PepijnSenders** [comment]
Hey @mxstbr, I will check it out today, thanks for appreciating our work :)

**Comment by PhiLhoSoft** [comment]
I can be wrong, but I get the impression that styled-components is React only.
This project abandoned React to render the tests, using only ES6 templates to generate the HTML. So, somehow, it focuses on libraries that are agnostic to the view library.
If styled-components can be used in this context, I would love to see how. 😄

**Comment by mxstbr** [comment]
> This project abandoned React to render the tests, using only ES6 templates to generate the HTML. So, somehow, it focuses on libraries that are agnostic to the view library.

Ah sorry, I didn't realize that! Yes indeed, `styled-components` is React only. In that case we might not be able to get a good comparison 😢

**Comment by PepijnSenders** [comment]
I checked it out and saw that, forgot to respond, sorry!
